repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    # Check yaml files like this one and github actions if they are valid
  - id: check-yaml
    # Check toml files like pyproject.toml if it is valid
  - id: check-toml
    # Check if python files are valid
  - id: check-ast
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements

# Check github action workflow files
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.22.0
  hooks:
  - id: check-github-workflows

# Convert relative to absolute imports
- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
  - id: absolufy-imports

- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
  # Check for bad code
  - id: python-no-eval
  - id: python-no-log-warn
  # Enforce type annotation instead of comment annotation
  - id: python-use-type-annotations
